...
                        "ts": utc_now_iso(),
                        "category": "consciousness",
                        "model": model,  # ← added: track model for budget breakdown
                    })
...